// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.Generic.RabbitListener._consumer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.Generic.RabbitListener.funcProcessBytesRecieved")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.RabbitBase._connection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.RabbitBase._channel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.RabbitBase._serializer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.RabbitBase.ConnectionMananger")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.Generic.SenderFactory`1._messagingSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1405:Debug.Assert must provide message text", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~M:Next.Search.Messaging.Rabbit.Generic.RendezvousManager.ProcessBytesRecieved(RabbitMQ.Client.Events.BasicDeliverEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.Generic.RendezvousManager.RendezvousGroups")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1618:Generic type parameters must be documented", Justification = "Will come back to this", Scope = "type", Target = "~T:Next.Search.Messaging.Rabbit.Generic.IBasicRabbitMessage`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single class", Justification = "Intended", Scope = "type", Target = "~T:Next.Search.Messaging.Rabbit.Generic.RendezvousManager`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1001:Commas must be spaced correctly", Justification = "Intended", Scope = "type", Target = "~T:Next.Search.Messaging.Rabbit.Generic.RendezvousManager`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.Generic.RendezvousGroup.TicketsRecievedBack")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields must be private", Justification = "By design but need to check if this does have an effect if we do change to private", Scope = "member", Target = "~F:Next.Search.Messaging.Rabbit.Generic.RendezvousGroup.TicketsTaken")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single class", Justification = "Intended", Scope = "type", Target = "~T:Next.Search.Messaging.Rabbit.Generic.RendezvousGroup`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1001:Commas must be spaced correctly", Justification = "Intended", Scope = "type", Target = "~T:Next.Search.Messaging.Rabbit.Generic.RendezvousGroup`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1405:Debug.Assert must provide message text", Justification = "Intended", Scope = "member", Target = "~M:Next.Search.Messaging.Rabbit.Generic.RabbitSender`1.Send(Next.Search.Messaging.Generic.IMessageEnvelope{`0})")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single class", Justification = "Intended", Scope = "type", Target = "~T:Next.Search.Messaging.Rabbit.Generic.RendezvousCompleteEventArgs`2")]